// Real Mayura Indian Restaurant menu content, transcribed from
// https://mayura-indian-restaurant.com/menu/ — update here to keep the site in sync.
const MAYURA_MENU = [
  { cat: "Vegetarian Appetizers", items: [
    ["Vegetable Samosa", "7.95", "Two deep-fried crispy crusts stuffed with mashed potatoes and peas.", "v"],
    ["Mixed Vegetable Pakora", "12.95", "Vegetables dipped in chickpea flour with spices and deep-fried.", "v"],
    ["Onion Pakora", "12.95", "Sliced onions dipped in chickpea flour and deep-fried.", "v"],
    ["Idly, 3 Pieces", "9.95", "Three lentil and rice patties served with chutneys and sambar.", "vg,gf"],
    ["Podi Idly", "13.95", "Three pieces of idly roasted in chutney powder, onions and spices.", "vg,gf"],
    ["Medhu Vada, 3 Pieces", "10.95", "Three deep-fried lentil donuts.", "vg"],
    ["Dahi Vada", "13.95", "Two vadas dipped in yogurt sauce and garnished with cilantro.", "v"],
    ["Bhel Puri", "12.95", "Tomatoes, onions and boiled potatoes with tamarind chutney and cilantro.", "vg"],
    ["Banana Fry", "11.95", "Sliced ripe plantains deep-fried in rice flour batter.", "vg"],
    ["Samosa Chaat", "13.95", "Samosas topped with creamy yogurt, tangy chutneys and savory spices.", "v"],
    ["Paneer Pakora", "11.95", "Crispy fried paneer with a hint of spices.", "v"],
  ]},
  { cat: "Non-Vegetarian Appetizers", items: [
    ["Honey Glazed Chicken Wings", "16.95", "Wings coated in a Kerala-inspired honey sauce."],
    ["Shrimp Symphony", "17.95", "Golden prawns tossed in a bold, tangy glaze."],
    ["Chicken Kothu Porotta", "18.95", "Tender chicken stir-fried with shredded porotta and spices."],
    ["Navaa Chicken Fry", "18.95", "Traditionally spiced chicken, marinated and fried to perfection."],
    ["Chicken 65", "22.95", "Marinated boneless chicken deep-fried with South Indian spices.", "spicy"],
  ]},
  { cat: "Uthappam", items: [
    ["Plain Uthappam", "14.95", "Pancake made from rice and lentil batter.", "vg,gf"],
    ["Onion Uthappam", "16.95", "Rice and lentil pancake with onions.", "vg,gf"],
    ["Onion & Hot Chili Uthappam", "17.95", "Rice and lentil pancake with onions and chilies.", "vg,gf,spicy"],
    ["Vegetable Uthappam", "18.95", "Rice and lentil pancake with mixed vegetables.", "vg,gf"],
    ["Mayura Special Cheese & Veggie Uthappam", "19.95", "Rice and lentil pancake with cheese and mixed vegetables.", "v"],
    ["Five Cocktail Uthappam", "26.95", "Chef's choice of five varieties of mini uthappam, served with chana curry.", "v"],
  ]},
  { cat: "Dosas", items: [
    ["Plain Dosa", "13.95", "Golden-grilled crispy crepe made from fermented rice and lentil batter.", "vg,gf"],
    ["Masala Dosa", "15.95", "Golden-grilled crepe filled with mildly spiced mashed potatoes.", "vg,gf"],
    ["Ghee Roast", "15.95", "Crispy crepe roasted in melted butter.", "v,gf"],
    ["Paper Dosa", "16.95", "Paper-thin rolled crispy crepe.", "vg,gf"],
    ["Cheese Dosa", "19.95", "Crispy crepe stuffed with onions, tomatoes and mozzarella cheese.", "v"],
    ["Paneer Bhurji Dosa", "19.95", "Crispy crepe stuffed with flavorful Indian cottage cheese.", "v"],
    ["Sada Mysore Dosa", "15.95", "Plain crispy crepe with a spicy chutney spread.", "vg,gf,spicy"],
    ["Podi Dosa", "16.95", "Crepe sprinkled with flavorful spicy lentil powder.", "vg,gf,spicy"],
  ]},
  { cat: "Vegetarian Dishes", items: [
    ["Aloo Gobi", "18.95", "Potatoes and cauliflower cooked in a savory sauce.", "vg,gf"],
    ["Chana Masala", "19.95", "Garbanzo beans cooked with exotic spices.", "vg,gf"],
    ["Vegetable Korma", "18.95", "Mixed vegetables cooked in a coconut sauce.", "vg,gf"],
    ["Palak Paneer", "20.95", "Indian cottage cheese cooked with puréed spinach and spices.", "v,gf"],
    ["Paneer Butter Masala", "20.95", "Indian cottage cheese cooked in a silky-smooth tomato gravy.", "v,gf"],
    ["Kerala Special Avial", "19.95", "Mixed vegetables cooked with coconut and spices.", "vg,gf"],
    ["Oyster Mushroom Curry", "21.95", "Mushrooms cooked in coconut milk with subtle Kerala spices.", "vg,gf"],
    ["Poriyal", "17.95", "Fresh green beans or cabbage sautéed with traditional seasonings.", "vg,gf"],
  ]},
  { cat: "Chicken Dishes", items: [
    ["Butter Chicken", "23.95", "Grilled chicken cooked in a smooth, creamy cashew and tomato gravy.", "gf"],
    ["Kerala Special Chicken Curry", "22.95", "Boneless chicken cooked in curry sauce with coconut milk.", "gf"],
    ["Chettinad Chicken", "23.95", "Chicken cooked in the traditional style of Tamil Nadu, southern India.", "spicy,gf"],
    ["Chicken Tikka Masala", "23.95", "Boneless chicken tikka cooked in a savory tomato sauce.", "gf"],
    ["Chicken Tandoori", "22.95", "Marinated bone-in chicken cooked in a tandoor oven.", "gf"],
    ["Chicken Vindaloo", "22.95", "Chicken and potatoes cooked in a spicy sauce.", "spicy,gf"],
  ]},
  { cat: "Meats & Seafood", items: [
    ["Lamb Korma", "23.95", "Lamb cooked in a delicious blend of spices.", "gf"],
    ["Lamb Vindaloo", "23.95", "Lamb and potatoes cooked in a spicy sauce.", "spicy,gf"],
    ["Goat Curry", "24.95", "Chunks of goat and potatoes cooked in a spicy sauce.", "spicy,gf"],
    ["Fish Curry", "23.95", "Fish cooked in a savory gravy.", "gf"],
    ["Branzino Fish Fry", "23.95", "Shallow-fried marinated whole fish.", "gf"],
    ["Shrimp Masala", "24.95", "Shrimp cooked in a savory curry sauce.", "gf"],
  ]},
  { cat: "Navaa Specials", items: [
    ["Kappa, Yucca & Fish Curry", "27.95", "Traditional kappa or chakka served with a spicy, tangy coastal fish curry.", "spicy,gf"],
    ["Malabar Chicken Coconut Roast", "22.95", "Chicken slow-roasted with coconut, aromatic masala and spices.", "gf"],
    ["Malabar Shrimp Coconut Roast", "24.95", "Juicy shrimp roasted with coconut and spices, coastal Kerala style.", "gf"],
    ["Kerala Special Fish Pollichathu", "25.95", "Kerala-style fish wrapped in a banana leaf and grilled with traditional spices.", "gf"],
  ]},
  { cat: "Curry Specials", items: [
    ["Kottayam Red Curry", "24.95", "Spicy Kottayam-style fish curry with roasted spices and tangy notes.", "spicy,gf"],
    ["Navaa Salmon Mango Curry", "23.95", "Creamy salmon curry cooked with ripe mango and Kerala spices.", "gf"],
    ["Navaa Shrimp Molee", "23.95", "Tender shrimp cooked in coconut milk with gentle Kerala spices.", "gf"],
  ]},
  { cat: "Biryanis", items: [
    ["Thalassery Vegetable Biryani", "21.95", "Mixed vegetables cooked with aromatic jeerakasala rice and spices.", "vg"],
    ["Thalassery Chicken Biryani", "23.95", "Tender chicken cooked with aromatic jeerakasala rice and spices."],
    ["Thalassery Mutton Biryani", "25.95", "Marinated mutton cooked with aromatic jeerakasala rice and spices."],
    ["Thalassery Shrimp Biryani", "26.95", "Marinated shrimp cooked with aromatic jeerakasala rice and spices."],
  ]},
  { cat: "Indian Breads", items: [
    ["Plain Naan", "3.95", "White bread cooked in a tandoor.", "v"],
    ["Garlic Naan", "4.95", "Naan topped with garlic and cilantro.", "v"],
    ["Mayura Special Appam", "2.50", "Gluten-free bread made from fermented rice.", "vg,gf"],
    ["Porotta", "2.95", "Multi-layered flatbread.", "v"],
    ["Chapati", "2.00", "Whole-wheat bread cooked over an open flame.", "vg"],
  ]},
  { cat: "Rice, Fried Rice & Noodles", items: [
    ["Lemon Rice", "20.95", "Zesty lemon-flavored rice, light, refreshing and tangy.", "vg,gf"],
    ["Tamarind Rice", "20.95", "Tangy tamarind rice, mildly spiced and aromatic.", "vg,gf"],
    ["Vegetable Fried Rice", "22.95", "Wok-tossed rice with fresh vegetables, soy sauce and aromatics.", "vg"],
    ["Chicken Fried Rice", "24.95", "Juicy chicken stir-fried with rice, vegetables and savory sauces."],
    ["Chilli Chicken", "25.95", "Tender chicken cooked in a bold and spicy chili sauce.", "spicy"],
  ]},
  { cat: "Mayura Specials & Thali", items: [
    ["Kerala Special with Chicken Curry", "26.95", "Choice of bread served with Kerala chicken curry."],
    ["Kerala Special with Fish Curry", "27.95", "Choice of bread served with Kerala fish curry.", "gf"],
    ["Vegetarian Thali", "22.95", "Assorted vegetarian dishes served with rice, naan and a sweet. Dine-in only.", "v"],
    ["Non-Vegetarian Thali", "24.95", "Assorted dishes served with chicken or fish. Dine-in only."],
    ["Upma", "20.95", "Dry-roasted semolina cooked into a thick porridge with spices.", "v"],
  ]},
  { cat: "Desserts & Beverages", items: [
    ["Carrot Halwa", "11.95", "Sweet pudding made with shredded carrots and milk.", "v,gf"],
    ["Gulab Jamun", "8.95", "Deep-fried milk solids served in flavored sugar syrup.", "v"],
    ["Ras Malai", "8.95", "Sweet paneer dumplings soaked in cardamom-flavored cream.", "v,gf"],
    ["Indian Chai Tea", "5.95", "", "v"],
    ["Filter Coffee", "6.95", "", "v"],
    ["Lassi", "4.95", "Choice of mango, salted or sweet.", "v,gf"],
    ["Mango Juice", "4.95", "", "vg,gf"],
  ]},
];
window.MAYURA_MENU = MAYURA_MENU;
